app = "compta-app"

[build]
  # use the Dockerfile already in the repository
  dockerfile = "Dockerfile"

[env]
  DATABASE_URL = "postgresql://root:W9Ef3i4w32hj5xFzxfqfPvZeXKINTXLj@dpg-d6kic49aae7s73ae0l20-a/compta_duko"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
