// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dadaApp.Data;

#nullable disable

namespace dadaApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129150505_CorrigerDateTimeUTC")]
    partial class CorrigerDateTimeUTC
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("dadaApp.Models.Compte", b =>
                {
                    b.Property<int>("CompteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("compte_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompteId"));

                    b.Property<string>("CodeClient")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code_client");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<string>("NomClient")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nom_client");

                    b.Property<string>("NumeroCompte")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_compte");

                    b.HasKey("CompteId");

                    b.HasIndex("NumeroCompte", "CodeClient")
                        .IsUnique();

                    b.ToTable("Comptes", (string)null);
                });

            modelBuilder.Entity("dadaApp.Models.Ecriture", b =>
                {
                    b.Property<int>("EcritureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ecriture_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EcritureId"));

                    b.Property<string>("CodeJournal")
                        .HasColumnType("text")
                        .HasColumnName("code_journal");

                    b.Property<int>("CompteId")
                        .HasColumnType("integer")
                        .HasColumnName("compte_id");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("credit");

                    b.Property<DateTime>("DateComptable")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_comptable");

                    b.Property<DateTime?>("DateEcheance")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_echeance");

                    b.Property<DateTime?>("DateFacture")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_facture");

                    b.Property<DateTime>("DateSaisie")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_saisie");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("debit");

                    b.Property<string>("Libelle")
                        .HasColumnType("text")
                        .HasColumnName("libelle");

                    b.Property<string>("NumeroLettrage")
                        .HasColumnType("text")
                        .HasColumnName("numero_lettrage");

                    b.Property<string>("NumeroPiece")
                        .HasColumnType("text")
                        .HasColumnName("numero_piece");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.HasKey("EcritureId");

                    b.HasIndex("CompteId");

                    b.ToTable("Ecritures", (string)null);
                });

            modelBuilder.Entity("dadaApp.Models.LettrageManuel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeClient")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EcrituresJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomClient")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NumeroLettrage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalCredit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalDebit")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("LettragesManuels");
                });

            modelBuilder.Entity("dadaApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("dadaApp.Models.VueSoldeCompte", b =>
                {
                    b.Property<int>("CompteId")
                        .HasColumnType("integer")
                        .HasColumnName("CompteId");

                    b.Property<string>("NomClient")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NomClient");

                    b.Property<string>("NumeroCompte")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NumeroCompte");

                    b.Property<decimal?>("Solde")
                        .HasColumnType("numeric")
                        .HasColumnName("Solde");

                    b.Property<decimal?>("TotalCredit")
                        .HasColumnType("numeric")
                        .HasColumnName("TotalCredit");

                    b.Property<decimal?>("TotalDebit")
                        .HasColumnType("numeric")
                        .HasColumnName("TotalDebit");

                    b.ToTable("VueSoldesComptes");

                    b.ToView("VueSoldesComptes", (string)null);
                });

            modelBuilder.Entity("dadaApp.Models.Ecriture", b =>
                {
                    b.HasOne("dadaApp.Models.Compte", "Compte")
                        .WithMany("Ecritures")
                        .HasForeignKey("CompteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");
                });

            modelBuilder.Entity("dadaApp.Models.Compte", b =>
                {
                    b.Navigation("Ecritures");
                });
#pragma warning restore 612, 618
        }
    }
}
